server:
  port: 8001

spring:
  application:
    name: AUTH-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka:8760/eureka
      defaultZone: http://localhost:8760/eureka
token:
  expiration_time: 86400000
  secret: user_token
