server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    enabled: true
    key-store-password:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8760/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/user-background,/user-service/background
          filters:
            - AuthorizationHeaderFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/user,/user-service/user/isUser, /user-service/user/token
            - Method=Post
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/user/**
            - Method=Get,Delete
          filters:
            - AuthorizationHeaderFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/user/logout/**, /user-service/user/background
            - Method=Post
          filters:
            - AuthorizationHeaderFilter
        - id: social-service
          uri: lb://SOCIAL-SERVICE
          predicates:
            - Path=/social-service/**
          filters:
            - AuthorizationHeaderFilter

        - id: character-service
          uri: lb://CHARACTER-SERVICE
          predicates:
            - Path=/character-service/**
          filters:
            - AuthorizationHeaderFilter